apiVersion: v1
kind: Service
metadata:
  name: {{ include "helios.fullname" . }}-api
  labels:
    {{- include "helios.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "helios.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
---
{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helios.fullname" . }}-dashboard
  labels:
    {{- include "helios.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  type: {{ .Values.dashboard.service.type }}
  selector:
    {{- include "helios.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  ports:
    - name: http
      port: {{ .Values.dashboard.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
