import type { CostSummary, DriftReport } from './types';

export const MOCK_RESOURCE_SUMMARY = {
  total: 847,
  edgeCount: 2340,
  byType: {
    'ec2:instance':       214,
    's3:bucket':          187,
    'lambda:function':    143,
    'ec2:security-group': 141,
    'rds:db-instance':     42,
    'ec2:volume':          68,
    'ec2:subnet':          52,
  },
  byRegion: {
    'us-east-1':    412,
    'us-west-2':    218,
    'eu-west-1':    147,
    'ap-southeast-1': 70,
  },
  byStatus: {
    active:     712,
    stopped:     89,
    terminated:  31,
    pending:     15,
  },
  orphaned: 23,
};

export const MOCK_COST_SUMMARY: CostSummary = {
  totalMonthlyCost: 24810,
  totalAnnualCost: 297720,
  potentialMonthlySavings: 5412,
  potentialAnnualSavings: 64944,
  savingsPercentage: 21.8,
  recommendations: [
    {
      resourceId: 'i-0abc1234567890abc',
      resourceType: 'ec2:instance',
      region: 'us-east-1',
      action: 'rightsize',
      currentConfig: 'm5.2xlarge',
      recommendedConfig: 'm5.large',
      currentMonthlyCost: 276.48,
      projectedMonthlyCost: 69.12,
      monthlySavings: 207.36,
      annualSavings: 2488.32,
      confidenceScore: 0.97,
      rationale: 'Avg CPU 6.2%, max 18%. Consistent pattern over 30 days.',
      effort: 'medium',
      risk: 'low',
      implementationSteps: [],
    },
    {
      resourceId: 'db-prod-main',
      resourceType: 'rds:db-instance',
      region: 'us-east-1',
      action: 'rightsize',
      currentConfig: 'db.r5.xlarge',
      recommendedConfig: 'db.r5.large',
      currentMonthlyCost: 518.40,
      projectedMonthlyCost: 259.20,
      monthlySavings: 259.20,
      annualSavings: 3110.40,
      confidenceScore: 0.91,
      rationale: 'Memory utilization avg 28%. Safe to downsize with connection pooling.',
      effort: 'medium',
      risk: 'low',
      implementationSteps: [],
    },
    {
      resourceId: 'i-0def456idle',
      resourceType: 'ec2:instance',
      region: 'us-west-2',
      action: 'terminate',
      currentConfig: 'm5.xlarge',
      recommendedConfig: 'none (terminate)',
      currentMonthlyCost: 138.24,
      projectedMonthlyCost: 0,
      monthlySavings: 138.24,
      annualSavings: 1658.88,
      confidenceScore: 0.95,
      rationale: 'Instance idle for 31 days. CPU avg 0.3%, zero traffic.',
      effort: 'low',
      risk: 'medium',
      implementationSteps: [],
    },
    {
      resourceId: 'i-0ghi789',
      resourceType: 'ec2:instance',
      region: 'us-east-1',
      action: 'savings-plan',
      currentConfig: 'on-demand',
      recommendedConfig: '1-year-savings-plan',
      currentMonthlyCost: 276.48,
      projectedMonthlyCost: 174.18,
      monthlySavings: 102.30,
      annualSavings: 1227.60,
      confidenceScore: 0.90,
      rationale: '90%+ utilization over 60 days. Savings Plan saves 37%.',
      effort: 'low',
      risk: 'low',
      implementationSteps: [],
    },
    {
      resourceId: 'vol-0abc123unattached',
      resourceType: 'ec2:volume',
      region: 'us-east-1',
      action: 'delete-snapshot',
      currentConfig: '500GB gp2 (unattached)',
      recommendedConfig: 'delete',
      currentMonthlyCost: 50.00,
      projectedMonthlyCost: 0,
      monthlySavings: 50.00,
      annualSavings: 600.00,
      confidenceScore: 0.99,
      rationale: 'EBS volume unattached for 45 days.',
      effort: 'low',
      risk: 'medium',
      implementationSteps: [],
    },
  ],
  byProvider:      { aws: 24810 },
  byRegion:        { 'us-east-1': 14200, 'us-west-2': 6800, 'eu-west-1': 3810 },
  byResourceType:  { 'ec2:instance': 12400, 'rds:db-instance': 6200, 'lambda:function': 3800, 'other': 2410 },
  trend: [
    { date: '2025-12', amount: 22100, provider: 'aws' },
    { date: '2026-01', amount: 23400, provider: 'aws' },
    { date: '2026-02', amount: 22800, provider: 'aws' },
    { date: '2026-03', amount: 25100, provider: 'aws' },
    { date: '2026-04', amount: 24200, provider: 'aws' },
    { date: '2026-05', amount: 24810, provider: 'aws' },
  ],
};

export const MOCK_VIOLATIONS = {
  total: 14,
  violations: [
    { ruleId: 'cis-1.4',  ruleName: 'Access key rotation',      resourceId: 'iam-user-deploy', resourceType: 'iam:user',     region: 'global',    severity: 'high'     as const, message: '3 IAM users have access keys older than 90 days',    evidence: {}, detectedAt: new Date().toISOString(), remediationGuidance: 'Rotate access keys via IAM console', autoRemediatable: false },
    { ruleId: 'cis-2.1',  ruleName: 'CloudTrail all regions',   resourceId: 'trail-main',      resourceType: 'cloudtrail',   region: 'us-west-1', severity: 'critical' as const, message: 'CloudTrail not enabled in us-west-1, ap-northeast-1', evidence: {}, detectedAt: new Date().toISOString(), remediationGuidance: 'Enable CloudTrail multi-region', autoRemediatable: true  },
    { ruleId: 'cis-2.9',  ruleName: 'S3 bucket not public',     resourceId: 'my-public-bucket',resourceType: 's3:bucket',    region: 'us-east-1', severity: 'critical' as const, message: 'S3 bucket has public read access enabled',           evidence: {}, detectedAt: new Date().toISOString(), remediationGuidance: 'Block public access in S3 settings',  autoRemediatable: true  },
    { ruleId: 'cis-4.1',  ruleName: 'No SSH from 0.0.0.0/0',   resourceId: 'sg-0abc123',      resourceType: 'ec2:security-group', region: 'us-east-1', severity: 'high' as const, message: 'Security group allows SSH from 0.0.0.0/0',      evidence: {}, detectedAt: new Date().toISOString(), remediationGuidance: 'Restrict port 22 to known CIDRs',     autoRemediatable: false },
    { ruleId: 'cis-3.1',  ruleName: 'VPC flow logs enabled',    resourceId: 'vpc-0def456',     resourceType: 'ec2:vpc',      region: 'eu-west-1', severity: 'medium'   as const, message: 'VPC in eu-west-1 has no flow logs configured',       evidence: {}, detectedAt: new Date().toISOString(), remediationGuidance: 'Enable VPC flow logs to CloudWatch',  autoRemediatable: true  },
  ],
};
